project:
  type: website
  output-dir: docs

website:
  title: "M244 Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes.qmd
        text: Data
      - href: Methods.qmd
        text: Methods
      - href: Visualizations.qmd
        text: Visuals
      - href: Results.qmd
        text: Results
      - href: Discussion.qmd
        text: Discussion

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



