---
title: "Discussion"
format: 
  html:
    page-layout: full
    theme: cosmo
    toc: true
    toc-title: "Contents"
    embed-resources: true
    standalone: true
editor: 
  markdown: 
    wrap: 72
---

Through our clustering analysis we were able to conclude that movies with a higher budget tend to have a higher world gross value. From our regression analysis we found that audience score, the number of theaters showing movie opening week, and the box office average revenue opening weekend have a significant relationship with profitability and world gross. Based on the patterns in our clustering analysis, movies with a higher budget are more likely to yield a higher world gross and be more successful. From our regression results we can conclude that there is a stronger positive relationship with the significant variables listed above with our outcomes, suggesting that for a movie to be more successful in both profitability and world gross, producers should target those three predictor variables. Combining the conclusions from both models, we might suggest to movie producers looking to maximize their success to aim for a high budget, audience score, and to play the movie in a lot of theaters opening weekend.

Our analysis was not without limitations, the largest of which is the time frame our dataset comes from. The data only encompassed 2007-2013, and because that is over a decade ago we cannot make as convincing an argument for how to predict the success of movies being released today. Another limitation of our data is that it only includes Hollywood movies and not independent or foreign films, making it hard to apply our results to those movies. During our data cleaning when we filtered out our missing variables, there was a lot of categorical data that was missing and caused our number of observations to shrink. 

For future investigations that expand the scope of our research, it is possible to run our analysis on a set of movie data containing more recent movies, since there are a significant amount of influential movies produced within the past 10 years. Also, people can perform analysis on a dataset covering worldwide movies instead of only Hollywood movies. This way, a more comprehensive pattern for movies from other countries can also be detected. Moreover, people can apply other movie rating sources, since Rotten Tomatoes are mostly not statistically significant, it will be supportive to use other rating sources other than Audience Score to justify the results. 
