---
title: "Methodology"
format: 
  html:
    page-layout: full
    theme: cosmo
    toc: true
    toc-title: "Contents"
    embed-resources: true
    standalone: true
editor: 
  markdown: 
    wrap: 72
---

We started our initial investigation by cleaning the dataset. First, we had to make sure that all the variables that were in units of money were in millions of dollars. We replaced the BOAvgOpenWeekend column to be in units of millions, and we calculated that column by taking OpeningWeekend and dividing it by TheatersOpenWeek. After we made that change, we deleted missing observations from the dataset so that we could create visualizations and do analysis without the influence of empty entries.

Under the visualization part, the goal is to use plausible plots to illustrate the relationships between our outcome and explanatory variables. We used suitable visualization methods and statistical models to help support our analysis. First, we created scatter plots to examine various relationships with the genre variable (Figures 1 and 2). Next, we used side-by-side box plots to visualize the relationship between Rotten Tomatoes and audience score with world gross (Figure 3). We also created another scatter plot to show the relationship between the number of theaters showing a movie on opening weekend, and the revenue the movie made for opening weekend (Figure 4). By using scatterplots, it is possible to demonstrate the distribution of data and try to interpret the underlying reason for the distribution trend. For boxplots, it can be more straightforward to horizontally compare the range, median, and mean across different groups.

Because one of our outcome variables is profitability, we chose to do a clustering analysis on budget and world gross to find patterns related to a movie’s profitability. Budget and world gross contribute to a movie’s profitability, so by using a clustering model, we were able to analyze patterns in the variables that contribute to profitability. We used k-means clustering and grouped the Budget column into five groups all of different budget ranges. To visualize the clustering relationship, we build a box plot to show the relationship between the five clusters and the world gross (Figure 5).

We also chose to use a multilinear regression model to analyze several of our variables together and analyze how they contribute to predicting the outcome variables. After our exploratory data analysis, we chose to analyze audience and Rotten Tomatoes scores, genre, the number of theaters showing the movie opening weekend, and the box office average for opening weekend. We made a regression model with both profitability and world gross as outcomes to test our predictors against both and compare the results (Results shown at bottom of Visuals page).
